### KFold Cross Validation -- The Verbose Way

In class we discussed cross validation, with the idea that it gives us a more thorough way of testing the validity of our model.  

To illustrate how it works, we used the function `cross_val_score()` from the `model_selection` module, which returns our individual validation scores from each round.  

The `cross_val_score()` function is useful and concise, but has the drawback that it doesn't allow you to see the index positions for each of your folds, which can be problematic if you want to examine the data in a specific validation set.  

This notebook will discuss the use of an alternative way to do KFold cross validation, using the `KFold` module, which is a more deliberate way of using the technique.

### Boston Housing Example

To demonstrate how the module works, we'll continue to use the boston housing dataset.

In [162]:
# import our modules
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.linear_model import LinearRegression

# import the dataset
df = pd.read_csv('../data/housing.csv')

# declare X & y
X = df.iloc[:, :-1]
y = df['PRICE']

# initialize model
lreg = LinearRegression()

In class we used a randomized training and test set and then used 10-Fold cross validation to determine the sensitivity of our data to potential outliers and variation in out of sample data.  Sample code looked like this:

In [163]:
# define training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2019)

In [164]:
# use cross_val_score to get our validation scores
scores = cross_val_score(estimator=lreg, X=X_train, y=y_train, cv=10)
scores

array([0.74469313, 0.72965599, 0.78482663, 0.65675571, 0.66315517,
       0.78283033, 0.81788242, 0.79596427, 0.5480151 , 0.75188945])

What stands out about these scores is their variation.  0.55 - 0.82 is a fairly wide range of r-squared values for a dataset.  What also stands out is the validation score in the 9th fold, which is much lower than the others.  

A natural question then is "what's so different about the data in that particular fold?"  

If you limit yourself to the `cross_val_score()` method you won't be able to look into the issue further.

### KFold Module

The `KFold` module allows one to examine data within a particular fold, if the issue is warranted.

Let's take a look at how it works.

In [165]:
# initialize it
kfold = KFold(n_splits=10)

When initialized, KFold has three parameters that can be set:

 - **n_splits**: integer, the number of folds to use in cross validation
 - **shuffle**: boolean, whether or not to shuffle your indices or use them in sequential order
 - **random_state**: the seed value to use when shuffling indices.  Only used if `shuffle` is set to `TRUE`
 
The `KFold` module has only one method of consequence:  `split()`, which returns a generator object of the indices to be used in validation and test sets for each subsequent fold.

In [166]:
# we'll use kfold to split our data into its indices
splits = list(kfold.split(X_train))

Two notes about the above line:

 - the `list()` method is used because a generator object doesn't allow you to lookup values at an index position
 - you could also payy `y` into the `split()` method as well.  the method just needs to something with an index.

The `splits` variable allows you then to access individual index values for each fold.

In [167]:
# the list has 10 items -- a tuple containing index positions the validation and test set in each fold
len(splits)

10

In [168]:
# each item in the list is a collection of two lists - one with the index positions for the test set, and one for the validation set
splits[0]

(array([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
        106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
        158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183,
        184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196,
        197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
        210, 211, 212, 213, 214, 215, 216, 217, 218

In [169]:
# these are the indices for the TEST set in ROUND 1 of KFold
splits[0][0]

array([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183,
       184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196,
       197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
       210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 22

In [170]:
# and these are the indices for the validation set in round 1
splits[0][1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40])

Let's make a small observation:  the index values from the `splits` variable are ordered, but the index values in our variables for `X_train` and `y_train` are not.  

For our results to be consistent with what we had from `cross_val_score()` we'll want to reset the index on our training set so it's monotonically increasing, like the index values in `splits`.

In [171]:
# notice how this has an unordered index, because it was shuffled?
X_train.head()

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX  \
249  0.19073  22.0   5.86     0  0.431  6.718   17.5  7.8265    7  330   
51   0.04337  21.0   5.64     0  0.439  6.115   63.0  6.8147    4  243   
151  1.49632   0.0  19.58     0  0.871  5.404  100.0  1.5916    5  403   
486  5.69175   0.0  18.10     0  0.583  6.114   79.8  3.5459   24  666   
235  0.33045   0.0   6.20     0  0.507  6.086   61.5  3.6519    8  307   

     PTRATIO       B  LSTAT  
249     19.1  393.74   6.56  
51      16.8  393.97   9.43  
151     14.7  341.60  13.28  
486     20.2  392.68  14.98  
235     17.4  376.75  10.88

In [172]:
# this will get the index values increasing stepwise from 0 to 403
X_train = X_train.reset_index()
y_train = y_train.reset_index()

# this will get rid of the 'index' column that pops up after you reset the index
X_train = X_train.drop('index', axis=1)
y_train = y_train.drop('index', axis=1)

How does one get this information to work for actual cross validation?  

The following for-loop would do the trick:

In [174]:
lreg = LinearRegression()
cross_val_scores = []

for test_idx, val_idx in kfold.split(X_train):
    lreg.fit(X_train.iloc[test_idx], y_train.iloc[test_idx])
    score = lreg.score(X_train.iloc[val_idx], y_train.iloc[val_idx])
    cross_val_scores.append(score)

Now if one looks at the validation scores returned from this, they exactly match what we had from the `cross_val_score()` method:

In [175]:
cross_val_scores

[0.7446931264241542,
 0.7296559896509521,
 0.7848266265881662,
 0.6567557105078086,
 0.6631551694581892,
 0.782830328560734,
 0.8178824192596486,
 0.7959642722807119,
 0.5480150991902277,
 0.7518894508603533]

So now, if we wanted to, we could use the values from the `splits` variable to get the index values for the 9th fold and go from there.

In [176]:
# these are the index values for the validation set in the 9th fold
val_idx = splits[8][1]

In [177]:
# and we can look at the original values in our dataset
X_train.iloc[val_idx]

CRIM     ZN  INDUS  CHAS     NOX     RM    AGE     DIS  RAD  TAX  \
324   0.07978   40.0   6.41     0  0.4470  6.482   32.1  4.1403    4  254   
325   2.73397    0.0  19.58     0  0.8710  5.597   94.9  1.5257    5  403   
326   0.04203   28.0  15.04     0  0.4640  6.442   53.6  3.6659    4  270   
327   4.54192    0.0  18.10     0  0.7700  6.398   88.0  2.5182   24  666   
328   0.06162    0.0   4.39     0  0.4420  5.898   52.3  8.0136    3  352   
329   0.03113    0.0   4.39     0  0.4420  6.014   48.5  8.0136    3  352   
330   0.04684    0.0   3.41     0  0.4890  6.417   66.1  3.0923    2  270   
331   0.08187    0.0   2.89     0  0.4450  7.820   36.9  3.4952    2  276   
332   0.03932    0.0   3.41     0  0.4890  6.405   73.9  3.0921    2  270   
333   0.01432  100.0   1.32     0  0.4110  6.816   40.5  8.3248    5  256   
334   0.03427    0.0   5.19     0  0.5150  5.869   46.3  5.2311    5  224   
335   1.19294    0.0  21.89     0  0.6240  6.326   97.7  2.2710    4  437   
336   0.10959    0.0  11.93     0  0.5730  6.794   89.3  2.3889    1  273   
337   0.55007   20.0   3.97     0  0.6470  7.206   91.6  1.9301    5  264   
338   0.43571    0.0  10.59     1  0.4890  5.344  100.0  3.8750    4  277   
339   0.02177   82.5   2.03     0  0.4150  7.610   15.7  6.2700    2  348   
340   0.22876    0.0   8.56     0  0.5200  6.405   85.4  2.7147    5  384   
341   0.03961    0.0   5.19     0  0.5150  6.037   34.5  5.9853    5  224   
342   4.89822    0.0  18.10     0  0.6310  4.970  100.0  1.3325   24  666   
343   2.37934    0.0  19.58     0  0.8710  6.130  100.0  1.4191    5  403   
344   7.40389    0.0  18.10     0  0.5970  5.617   97.9  1.4547   24  666   
345  14.05070    0.0  18.10     0  0.5970  6.657  100.0  1.5275   24  666   
346   0.06129   20.0   3.33     1  0.4429  7.645   49.7  5.2119    5  216   
347   8.26725    0.0  18.10     1  0.6680  5.875   89.6  1.1296   24  666   
348   0.65665   20.0   3.97     0  0.6470  6.842  100.0  2.0107    5  264   
349   0.13587    0.0  10.59     1  0.4890  6.064   59.1  4.2392    4  277   
350   0.55778    0.0  21.89     0  0.6240  6.335   98.2  2.1107    4  437   
351   0.24103    0.0   7.38     0  0.4930  6.083   43.7  5.4159    5  287   
352   0.10008    0.0   2.46     0  0.4880  6.563   95.6  2.8470    3  193   
353   0.17134    0.0  10.01     0  0.5470  5.928   88.2  2.4631    6  432   
354   0.32264    0.0  21.89     0  0.6240  5.942   93.5  1.9669    4  437   
355   9.72418    0.0  18.10     0  0.7400  6.406   97.2  2.0651   24  666   
356   0.03306    0.0   5.19     0  0.5150  6.059   37.3  4.8122    5  224   
357   0.36920    0.0   9.90     0  0.5440  6.567   87.3  3.6023    4  304   
358   0.12083    0.0   2.89     0  0.4450  8.069   76.0  3.4952    2  276   
359   0.30347    0.0   7.38     0  0.4930  6.312   28.9  5.4159    5  287   
360   0.04113   25.0   4.86     0  0.4260  6.727   33.5  5.4007    4  281   
361  15.17720    0.0  18.10     0  0.7400  6.152  100.0  1.9142   24  666   
362  25.94060    0.0  18.10     0  0.6790  5.304   89.1  1.6475   24  666   
363   0.08370   45.0   3.44     0  0.4370  7.185   38.9  4.5667    5  398   

     PTRATIO       B  LSTAT  
324     17.6  396.90   7.19  
325     14.7  351.85  21.45  
326     18.2  395.01   8.16  
327     20.2  374.56   7.79  
328     18.8  364.61  12.67  
329     18.8  385.64  10.53  
330     17.8  392.18   8.81  
331     18.0  393.53   3.57  
332     17.8  393.55   8.20  
333     15.1  392.90   3.95  
334     20.2  396.90   9.80  
335     21.2  396.90  12.26  
336     21.0  393.45   6.48  
337     13.0  387.89   8.10  
338     18.6  396.90  23.09  
339     14.7  395.38   3.11  
340     20.9   70.80  10.63  
341     20.2  396.90   8.01  
342     20.2  375.52   3.26  
343     14.7  172.91  27.80  
344     20.2  314.64  26.40  
345     20.2   35.05  21.22  
346     14.9  377.07   3.01  
347     20.2  347.88   8.88  
348     13.0  391.93   6.90  
349     18.6  381.32  14.66  
350     21.2  394.67  16.96  
351     19.

In [178]:
# and for the target variable
y_train.iloc[val_idx]

PRICE
324   29.1
325   15.4
326   22.9
327   25.0
328   17.2
329   17.5
330   22.6
331   43.8
332   22.0
333   31.6
334   19.5
335   19.6
336   22.0
337   36.5
338   20.0
339   42.3
340   18.6
341   21.1
342   50.0
343   13.8
344   17.2
345   17.2
346   46.0
347   50.0
348   30.1
349   24.4
350   18.1
351   22.2
352   32.5
353   18.3
354   17.4
355   17.1
356   20.6
357   23.8
358   38.7
359   23.0
360   28.0
361    8.7
362   10.4
363   34.9

To give an example of how this is helpful for future diagnostics, let's take a look at our errors for the validation set with the low r-squared values.

In [179]:
# get the index values for the training and validation sets in the 9th fold
val_idx  = splits[8][1]
test_idx = splits[8][0]

In [180]:
# fit on the test index
lreg.fit(X_train.iloc[test_idx], y_train.iloc[test_idx])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [181]:
# get the predictions for the validation index
preds = lreg.predict(X_train.iloc[val_idx])

In [185]:
# let's take a look at the error column for the validation set
np.abs((y_train.loc[val_idx] - preds)).sort_values(by='PRICE', ascending=False)

PRICE
342  30.353583
347  26.234526
331   6.868811
326   5.608272
332   5.259861
346   5.198142
362   4.968544
336   4.954204
330   4.530361
348   4.512531
344   4.436250
339   4.309962
338   3.737356
327   2.724117
351   2.304709
352   2.103571
357   1.984592
328   1.932909
353   1.763286
356   1.761604
340   1.121757
358   1.057150
359   1.036384
354   0.979993
349   0.948994
333   0.947181
324   0.926500
360   0.731769
334   0.679262
355   0.635742
345   0.601837
335   0.463829
329   0.454991
350   0.309089
361   0.295321
337   0.279890
363   0.137604
341   0.136067
343   0.076748
325   0.015293

Well, it's fairly obvious what's going on here.......about 80% of your squared error is being caused by two samples.  This is a natural point for follow up analysis.